dist: trusty
sudo: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'hvr-ghc', 'george-edison55-precise-backports' ]   # ge-55 : CMake
    packages: ['g++-5', 'gcc-5', 'expat', 'libgmp-dev', 'libpopt-dev', 'libboost-dev', 'flex', 'bison', 'libnuma-dev', 'liblzma-dev', 'dejagnu', 'libhwloc-dev', 'cmake', 'cmake-data']
    
# add 'asciidoc', 'xmlto', 'doxygen' for doc generation
# add 'ghc-7.10.3', 'ghc-7.10.3-dyn', 'happy-1.19.5', for SCOOP

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - export GCCVER='5'
  - export CXX=g++-${GCCVER}
  - export CC=gcc-${GCCVER}
  - export AR=gcc-ar-${GCCVER}
  - export RANLIB=gcc-ranlib-${GCCVER}
  - export NM=gcc-nm-${GCCVER}

# build spot
script :
  - ./tag.sh
  - wget --progress=dot:mega https://yanntm.github.io/Spot-BinaryBuilds/spot_linux.tar.gz
  - tar xzf spot_linux.tar.gz
  # This line to patch moved .la and .pc files that configure paths for linking in LTSmin/pkgconfig
  - export TARGET=$(pwd) ; cd usr/local/lib/pkgconfig/ ;  for i in *.pc ; do cat $i | sed  "s#=.*/usr/local#=$TARGET/usr/local#g" > tmp ; \mv tmp $i ; done ; cd ..;  for i in *.la ; do cat $i | sed  "s#='.*/usr/local#='$TARGET/usr/local#g" > tmp ; \mv tmp $i ; done  ; cd ../../.. 
  - ./build_ltsmin.sh
  - ls -lah website/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/
  upload-dir: build/$TRAVIS_BUILD_NUMBER
  on:
    branch: master
  
after_deploy:
  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"   -H "Travis-API-Version:3" -H "Authorization:token $APITOKEN" -d '{"request":{"message":"Triggered by LTSmin build.","branch":"master"}}' https://api.travis-ci.org/repo/yanntm%2FITS-Tools-pnmcc/requests
