# TODO : this file is not used currently : adapt for LTSmin

build:
  verbosity: minimal

clone_depth: 30

build_script :
 - C:\MinGW\bin\mingw-get install libgmpxx
 - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./build_spot.sh && mv website/spot_linux.tar.gz website/spot_windows.tar.gz"'
 - DIR

# - '%BASH_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; 7z a -tzip windows.zip usr/ "'
# SHELL=%BASH_PATH%
 
 
environment :
 MSYSTEM: MINGW64 
 BASH_PATH: C:\msys64\usr\bin\bash

 
artifacts:
  - path: website/spot_windows.tar.gz
    name: spot_windows.tar.gz

      